//
// Created by prem on 11/14/2018.
//

#ifndef FEATHER_CSS_RULE_TYPE_H
#define FEATHER_CSS_RULE_TYPE_H
namespace css {
    enum class CSSRuleType;
}
enum class css::CSSRuleType {
    UNKNOWN_RULE,
    STYLE_RULE,
    CHARSET_RULE,
    IMPORT_RULE,
    MEDIA_RULE,
    FONT_FACE_RULE,
    PAGE_RULE,
    KEYFRAMES_RULE,
    KEYFRAME_RULE,
    RESERVED_RULE,
    NAMESPACE_RULE,
    COUNTER_STYLE_RULE,
    SUPPORTS_RULE,
    DOCUMENT_RULE,
    FONT_FEATURE_VALUES_RULE,
    VIEWPORT_RULE,
    REGION_STYLE_RULE
};
#endif //FEATHER_CSS_RULE_TYPE_H
